### ISSUE TITLE
Squeezewave CPU implementation produces null wave file ( empty )

### ISSUE THREAD

**Issue by alokprasad** [KeigoTakamura/SqueezeWave-for-CPU-forkd-#1]
@KeigoTakamura san, i tried your CPU implemenation, which seems using non cuda calls.
but the output wav produces NULL/empty wave file . did u faced the same issue?

**Comment by KeigoTakamura** [comment]
Sorry.

The bug has not been fixed yet as stated in the TOME in the README, I think there is a problem somewhere in glow.py, but I am a novice to pytorch, so I have not yet identified the fix

**Comment by alokprasad** [comment]
@KeigoTakamura i was able to solve the issue have diff here.
https://github.com/alokprasad/binaries/blob/master/squeezewave.diff

**Comment by KeigoTakamura** [comment]
Thank you, I don't have the environment right now so I will test it later.

This repository is a temporary repository, so if the test is successful, we will recreate the repository and let you know!

**Comment by KeigoTakamura** [comment]
https://qiita.com/T_keigo_wwk/items/6f08a7079dbd8297af1d
https://github.com/KeigoTakamura/SqueezeWave


Thanks for throwing in a nice fix patch!

**Comment by KeigoTakamura** [comment]
There is no particular progress so it will be closed
